/// @description Method Binds

constant_state         = method(id, constant_state);
primary_actions        = method(id, primary_actions);
set_action_state       = method(id, character_set_action_state);
set_state_logic		   = method(id, character_set_state_logic);
set_action_animation   = method(id, character_set_action_animation);
movement_state		   = method(id, movement_state);
animation_state		   = method(id, animation_state);
attack_state           = method(id, attack_state);
receive_attack		   = method(id, receive_attack);
on_damage_done         = method(id, on_damage_done);
add_movement_input     = method(id, character_add_movement_input);
add_movement_direction = method(id, character_add_movement_direction);
add_movement_path      = method(id, character_add_movement_path);
add_impulse_position   = method(id, character_add_impulse_position);
add_impulse_direction  = method(id, character_add_impulse_direction);
add_impulse_x          = method(id, character_add_impulse_x);
add_impulse_y          = method(id, character_add_impulse_y);
add_impulse_z          = method(id, character_add_impulse_z);
add_constant_force     = method(id, character_add_constant_force);